// Shared product and data constants

export const PRODUCTS = [
  {
    id: 1,
    category: "Women's Kemis",
    name: 'Gold Tilet Classic Kemis',
    price: 189,
    oldPrice: null,
    image: '/assets/hero_model.png',
    rating: 4.9,
    reviews: 234,
    badge: 'bestseller',
    colors: ['#FFFDF9', '#E8D5B0', '#1C1810'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Handwoven by master artisans in Addis Ababa, this elegant Habesha Kemis features intricate gold Tilet embroidery along the collar, cuffs, and hemline.',
    origin: 'Addis Ababa, Ethiopia',
    material: '100% Handwoven Cotton',
    inStock: true,
  },
  {
    id: 2,
    category: "Men's Traditional",
    name: 'Royal Ceremonial Suit',
    price: 145,
    oldPrice: 180,
    image: '/assets/mens_outfit.png',
    rating: 4.8,
    reviews: 187,
    badge: 'new',
    colors: ['#FFFDF9', '#1C1810'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'A commanding traditional suit crafted for ceremonial and festive occasions. Features bold Tilet embroidery inspired by ancient Axumite patterns.',
    origin: 'Gondar, Ethiopia',
    material: '100% Handwoven Cotton',
    inStock: true,
  },
  {
    id: 3,
    category: 'Bridal Collection',
    name: 'Empress Bridal Kemis',
    price: 320,
    oldPrice: null,
    image: '/assets/wedding.png',
    rating: 5.0,
    reviews: 98,
    badge: 'bestseller',
    colors: ['#FFFDF9', '#F5EFE4'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    description: 'The pinnacle of bridal elegance. This luxurious Habesha Kemis is adorned with heavy gold thread Tilet and handcrafted exclusively for your most important day.',
    origin: 'Addis Ababa, Ethiopia',
    material: 'Premium Handwoven Silk-Cotton Blend',
    inStock: true,
  },
  {
    id: 4,
    category: 'Accessories',
    name: 'Artisan Silver Jewelry Set',
    price: 68,
    oldPrice: 90,
    image: '/assets/accessories.png',
    rating: 4.7,
    reviews: 312,
    badge: 'sale',
    colors: ['silver', '#C9A84C'],
    sizes: ['One Size'],
    description: 'Hand-hammered Ethiopian silver jewelry set including a Meskel cross pendant, earrings, and beaded necklace. Each piece is unique.',
    origin: 'Lalibela, Ethiopia',
    material: 'Sterling Silver & Traditional Beads',
    inStock: true,
  },
  {
    id: 5,
    category: "Children's Wear",
    name: 'Mini Heritage Family Set',
    price: 280,
    oldPrice: null,
    image: '/assets/children.png',
    rating: 4.9,
    reviews: 76,
    badge: 'new',
    colors: ['#FFFDF9'],
    sizes: ['3-4Y', '5-6Y', '7-8Y', '9-10Y'],
    description: 'Dress the whole family in authentic Habesha style! This coordinated set includes mini versions of the Gold Tilet Kemis for children.',
    origin: 'Addis Ababa, Ethiopia',
    material: '100% Handwoven Cotton',
    inStock: true,
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    text: "I ordered the Bridal Kemis for my traditional wedding ceremony and it was absolutely breathtaking. The embroidery is beyond stunning and the quality is incomparable. Every guest was in awe.",
    name: 'Meron Tadesse',
    location: 'Washington D.C., USA',
    rating: 5,
    avatar: null,
  },
  {
    id: 2,
    text: "Finally found a reliable source for authentic Ethiopian clothing in Europe. The shipping was fast, the quality is even better in person, and the customer service was exceptional throughout.",
    name: 'Sara Kifle',
    location: 'Stockholm, Sweden',
    rating: 5,
    avatar: null,
  },
  {
    id: 3,
    text: "I've been searching for high-quality traditional attire for my family reunion for years. Habesha Heritage delivered perfection — the custom tailoring service is incredible.",
    name: 'Biruk Hailu',
    location: 'Toronto, Canada',
    rating: 5,
    avatar: null,
  },
];

export const ORDERS = [
  { id: '#HH-8821', product: 'Gold Tilet Classic Kemis', sub: 'White · Size M', customer: 'Meron Tadesse', country: '🇺🇸 USA', status: 'delivered', date: 'Jul 8, 2025', amount: 189, image: '/assets/hero_model.png' },
  { id: '#HH-8820', product: 'Empress Bridal Kemis', sub: 'White Gold · Custom', customer: 'Sara Kifle', country: '🇸🇪 Sweden', status: 'shipped', date: 'Jul 7, 2025', amount: 320, image: '/assets/wedding.png' },
  { id: '#HH-8819', product: 'Royal Ceremonial Suit', sub: 'White · Size L', customer: 'Yonas Abebe', country: '🇨🇦 Canada', status: 'processing', date: 'Jul 7, 2025', amount: 145, image: '/assets/mens_outfit.png' },
  { id: '#HH-8818', product: 'Mini Heritage Family Set', sub: 'White · 3pc', customer: 'Biruk Hailu', country: '🇦🇺 Australia', status: 'delivered', date: 'Jul 6, 2025', amount: 280, image: '/assets/children.png' },
  { id: '#HH-8817', product: 'Artisan Silver Set', sub: 'Full Set', customer: 'Hana Tesfaye', country: '🇩🇪 Germany', status: 'pending', date: 'Jul 6, 2025', amount: 68, image: '/assets/accessories.png' },
];

export const REVENUE_DATA = [
  { day: 'Mon', thisWeek: 3200, lastWeek: 2100 },
  { day: 'Tue', thisWeek: 4100, lastWeek: 3400 },
  { day: 'Wed', thisWeek: 3800, lastWeek: 2900 },
  { day: 'Thu', thisWeek: 5800, lastWeek: 3700 },
  { day: 'Fri', thisWeek: 6200, lastWeek: 4800 },
  { day: 'Sat', thisWeek: 7900, lastWeek: 5100 },
  { day: 'Sun', thisWeek: 5400, lastWeek: 4200 },
];

export const AI_RESPONSES = [
  "Based on your store analytics, the **Gold Tilet Kemis** is your strongest performer this month with a 340% surge ahead of Timkat. I'd recommend increasing stock by at least 20 units and featuring it prominently on your storefront. 📈",
  "Great question! For a petite customer (under 5'3\"), I'd recommend sizing down one and requesting a shorter hemline of around 130cm. Our tailors can accommodate this with no extra charge on standard orders. ✂️",
  "Your conversion rate dipped slightly this week. Based on your visitor data, customers are dropping off on the product detail page. Consider adding a video of the embroidery process — stores that do this see a 28% boost in conversions. 🎥",
  "For the Timkat season in January, traditional white garments with gold embroidery see a 340% sales spike globally. I'd suggest starting a pre-order campaign now to capture the Ethiopian diaspora market in the US, UK, and Scandinavia. 🎉",
  "That's a lovely choice! The Gondar Palace Tilet pattern paired with your ivory fabric and gold thread would look stunning for a wedding reception. I can help you write a beautiful product description for that listing too. ✨",
];
